spring:
  application:
    name: financial-data-service
  datasource:
    url: jdbc:postgresql://localhost:5432/financial-data-db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}
          audiences: ${AUTH0_AUDIENCE}

external-api:
  open-exchange-rates:
    app-id: ${OPEN_EXCHANGE_RATES_APP_ID}
